export const items = [
    {
      title: 'Pendapatan',
      value: 12133310,
      description: 'Total uang yang diterima dari penjualan produk atau jasa sebelum dikurangi biaya-biaya.',
      isHeader: true,
    },
    {
      title: 'Harga Pokok Penjualan',
      value: 10462299,
      description: 'Biaya langsung yang terkait dengan produksi barang atau jasa yang dijual.',
      isHeader: true,
    },
    {
      title: 'Laba Kotor',
      value: -1671010,
      description: 'Selisih antara pendapatan dan harga pokok penjualan, menunjukkan keuntungan sebelum dikurangi beban operasional.',
      isHighlight: true,
      isNegative: true
    },
    {
      title: 'Beban Operasional:',
      description: 'Biaya-biaya yang dikeluarkan untuk menjalankan bisnis sehari-hari.',
      isSection: true,
    },
    { title: 'Gaji & Tunjangan Karyawan', value: 304968, description: 'Biaya untuk membayar gaji, bonus, dan tunjangan karyawan.' },
    { title: 'Biaya Pemasaran', value: 28567, description: 'Biaya untuk aktivitas promosi dan pemasaran produk atau jasa.' },
    { title: 'Beban Utiliti, Adm, Sewa & Lainnya', value: 374360, description: 'Biaya utilitas, administrasi, sewa gedung, dan biaya lainnya.' },
    { title: 'Biaya Perbaikan & Pemeliharaan', value: 7608, description: 'Biaya untuk memperbaiki dan memelihara aset perusahaan.' },
    { title: 'Biaya Penyusutan & Amortisasi', value: 71765, description: 'Biaya penurunan nilai aset tetap dan amortisasi aset tidak berwujud.' },
    { title: 'Jumlah Beban Operasional', value: 787267, description: 'Total seluruh beban operasional perusahaan.', isSubtotal: true },
    { title: 'Laba Operasi', value: 883744, description: 'Keuntungan yang dihasilkan dari aktivitas operasional utama perusahaan.', isHighlight: true },
    {
      title: 'Pendapatan (Beban) lain-lain:',
      description: 'Pendapatan atau biaya lain yang tidak terkait langsung dengan aktivitas utama perusahaan.',
      isSection: true,
    },
    { title: 'Beban Keuangan', value: -216840, description: 'Biaya bunga atau biaya keuangan lainnya.', isNegative: true },
    { title: 'Laba (Rugi) Selisih Kurs', value: -135044, description: 'Kerugian yang disebabkan oleh fluktuasi nilai tukar mata uang.', isNegative: true },
    { title: 'Lainnya', value: -1258, description: 'Pendapatan atau beban lain yang tidak dikategorikan.', isNegative: true },
    { title: 'Jumlah Pendapatan (Beban) lain-lain', value: -353142, description: 'Total pendapatan atau beban lain-lain.', isSubtotal: true },
    { title: 'Laba (Rugi) Sebelum Pajak', value: 530602, description: 'Keuntungan atau kerugian sebelum dikenakan pajak.', isHighlight: true },
  ];

export const quickStatBoxes = [
  {
    frontImage: 'https://th.bing.com/th/id/OIP.u0JGTBvpzHhxhNzVcSf3jQHaE8?rs=1&pid=ImgDetMain',
    backImage: 'https://s25.postimg.cc/hj4c4qnov/cta-3.png',
    title: "Profit and loss",
    description: "Analisis lengkap pendapatan dan pengeluaran perusahaan",
    metric: "32.5%"
  },
 
];

export const balanceSheetItems = [
    { title: 'ASET', isHeader: true },
    { title: 'Kas dan Bank', value: -7816674, isNegative: true, description: 'Saldo kas dan rekening bank perusahaan' },
    { title: 'Piutang Usaha', value: 18600058, description: 'Tagihan kepada pelanggan' },
    { title: 'Uang Muka', value: 462757, description: 'Pembayaran di muka untuk biaya operasional' },
    { title: 'Persediaan', value: 13316755, description: 'Nilai persediaan barang' },
    { title: 'Piutang Pemegang Saham', value: 3110054, description: 'Piutang kepada pemegang saham' },
    { title: 'Pajak Dibayar Dimuka', value: 236065, description: 'Pembayaran pajak di muka' },
    { title: 'Aset lancar lainnya', value: 200100, description: 'Aset lancar lainnya' },
    { title: 'Total Aset Lancar', value: 28109147, isSection: true, description: 'Total seluruh aset lancar' },
    { title: 'Aset Tetap (net)', isHeader: true },
    { title: 'Tanah', value: 7455080, description: 'Nilai tanah perusahaan' },
    { title: 'Gedung', value: 2029326, description: 'Nilai bangunan' },
    { title: 'Kendaraan', value: 2818374, description: 'Nilai kendaraan operasional' },
    { title: 'Mesin & Peralatan', value: 2372033, description: 'Nilai mesin dan peralatan' },
    { title: 'Inventaris Kantor', value: 99878, description: 'Nilai inventaris kantor' },
    { title: 'Total Aset Tetap (net)', value: 14769567, isSection: true, description: 'Total seluruh aset tetap' },
    { title: 'Aset tidak berwujud (net)', value: 14222, description: 'Total aset tidak berwujud' },
    { title: 'TOTAL ASET', value: 42889325, isHighlight: true, description: 'Total seluruh aset perusahaan' },
    { title: 'KEWAJIBAN', isHeader: true },
    { title: 'Utang Usaha', value: 5814480, description: 'Kewajiban kepada pemasok' },
    { title: 'Uang Muka Pelanggan', value: 1975578, description: 'Uang muka dari pelanggan' },
    { title: 'Utang Pajak', value: 445353, description: 'Kewajiban pajak yang harus dibayar' },
    { title: 'Utang Pemegang Saham', value: 0, description: 'Kewajiban kepada pemegang saham' },
    { title: 'Utang lainnya', value: 8679755, description: 'Kewajiban lainnya' },
    { title: 'Biaya Yang Masih Harus Dibayar', value: 3634, description: 'Biaya yang masih harus dibayar' },
    { title: 'Total Kewajiban Lancar', value: 16918800, isSection: true, description: 'Total kewajiban lancar' },
    { title: 'Utang Bank', value: 7903969, description: 'Kewajiban kepada bank' },
    { title: 'Total Kewajiban Jk.Panjang', value: 7903969, isSection: true, description: 'Total kewajiban jangka panjang' },
    { title: 'MODAL', isHeader: true },
    { title: 'Modal Saham', value: 501000, description: 'Modal saham perusahaan' },
    { title: 'Akumulasi Laba/(Rugi) Ditahan', value: 17565025, description: 'Akumulasi laba atau rugi yang ditahan' },
    { title: 'Laba/(Rugi) Berjalan', value: 531, description: 'Laba atau rugi periode berjalan' },
    { title: 'Total Modal', value: 17546376, isSection: true, description: 'Total modal perusahaan' },
    { title: 'TOTAL KEWAJIBAN DAN MODAL', value: 42363138, isHighlight: true, description: 'Total kewajiban dan modal' },
  ];